version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/zip/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: stop.sh # 엔진엑스와 연결되어 있지 않은 스프링 부트 종료
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: start.sh  # 엔진엑스와 연결되어 있지 않은 Port로 새 버전의 스프링 부트 시작
      timeout: 60
      runas: ubuntu
  ValidateService:
    - location: health.sh # 새 스프링 부트가 정상적으로 실행됐는지 확인
      runas: ubuntu